name: platform_detail
description: A lightweight library to obtain details of the current platform in a much more complete and simple way.
version: 5.1.0
homepage: https://github.com/vicajilau/platform_detail

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ">=10.1.0 <13.0.0"
  dio: ^5.8.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <7.0.0"
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

